[package]
name = "hohtokeilaus"
version = "0.1.0"
authors = ["Teemu Erkkola <teemu.erkkola@iki.fi>"]
edition = "2018"

[dependencies]
dotenv = "0.13.0"
actix = "0.7"
actix-web = "0.7"
serde = "1.0.88"
serde_derive = "1.0.88"
http = "0.1.7"

reqwest = "0.9.10"
